[REWORK] Introduced multi-stage docker build to reduce images size

diff --git a/setup/master/dockerfile/MasterFile b/setup/master/dockerfile/MasterFile
--- a/setup/master/dockerfile/MasterFile
+++ b/setup/master/dockerfile/MasterFile
@@ -1,5 +1,5 @@
 # - Base image --------------------------------
-FROM ubuntu:24.04
+FROM ubuntu:24.04 AS python-builder
 
 # - Environment --------------------------------
 ENV DEBIAN_FRONTEND=noninteractive \
@@ -27,15 +27,8 @@ RUN set -eux; \
         libsqlite3-dev \
         libbz2-dev \
         libpq-dev \
-        smbclient \
-        cifs-utils \
-        libfuse2 \
-        wget \
         curl; \
     \
-    # --- Node.js 22 LTS via NodeSource ---
-    curl -fsSL https://deb.nodesource.com/setup_22.x | bash - && \
-    apt-get install -y --no-install-recommends nodejs; \
     # add Deadsnakes PPA for Python 3.12
     add-apt-repository -y ppa:deadsnakes/ppa && \
     apt-get update -y && \
@@ -54,6 +47,51 @@ RUN set -eux; \
 COPY sources/requirements.txt /tmp/requirements.txt
 RUN set -eux; \
     python -m pip install --no-cache-dir --break-system-packages --ignore-installed -r /tmp/requirements.txt
+
+
+# - Base image --------------------------------
+FROM ubuntu:24.04 AS runtime
+
+# - Environment --------------------------------
+ENV DEBIAN_FRONTEND=noninteractive \
+    TZ=Europe/Minsk \
+    PATH="/OSIR/OSIR:${PATH}"
+
+# - System setup -------------------------------
+RUN set -eux; \
+    # Time-zone
+    ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ >/etc/timezone; \
+    \
+    # Core packages (single layer, no recommends)
+    apt-get update -y && \
+    apt-get upgrade -y && \
+    apt-get install -y --no-install-recommends \
+        software-properties-common \
+        smbclient \
+        cifs-utils \
+        libfuse2 \
+        libpq5 \
+        wget \
+        curl; \
+    \
+    # --- Node.js 22 LTS via NodeSource ---
+    curl -fsSL https://deb.nodesource.com/setup_22.x | bash - && \
+    apt-get install -y --no-install-recommends nodejs; \
+    # add Deadsnakes PPA for Python 3.12
+    add-apt-repository -y ppa:deadsnakes/ppa && \
+    apt-get update -y && \
+    apt-get install -y --no-install-recommends \
+        python3.12-full \
+        python3-pip; \
+    \
+    # make python3.12 the default python
+    update-alternatives --install /usr/bin/python python /usr/bin/python3.12 1; \
+    \
+    # Clean up APT cache to shrink image
+    apt-get clean && rm -rf /var/lib/apt/lists/*
+
+# - Python dependencies (cached layer) --------------------
+COPY --from=python-builder /usr/local /usr/local
 
 COPY sources/master_entrypoint.sh /usr/local/bin/entrypoint.sh
 RUN chmod +x /usr/local/bin/entrypoint.sh
